server:
  port: 9000

spring:
  application:
    name: demo
  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.crqlyooh7jfa.ap-northeast-2.rds.amazonaws.com/term_DB?autoReconnect=true&serverTimezone=UTC
    username: admin
    password: JiseopKim1031
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.example.demo.src: DEBUG