server:
  port: 9001

spring:
  application:
    name: demo
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/seopdb?autoReconnect=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.example.demo.src: DEBUG